type Plant {
    id: Int
    common_name: String
    slug: String
    scientific_name: String
    year: Int
    bibliography: String
    author: String
    status: String
    rank: String
    family_common_name: String
    genus_id: Int
    synonyms: [String]
    genus: String
    family: String
    image_url: String
}

type User {
    id: ID
    email: String
    plants: [Plant]
}

type Query {
    getPlants(
        id: String!
        link: String
        page_number: Int
        per_page: Int
        total: Int 
        total_pages: Int
        ): PlantConnection
}

type PlantConnection {
    cursor: String
    hasMore: Boolean
    plants: [Plant]
}
