type Plant {
    id: ID
    common_name: String
    complete_data: Boolean
    link: String
    scientific_name: String
    image_url: String
    slug: String
}

type User {
    id: ID
    email: String
    plants: [Plant]
}

type Query {
    getPlants(
        id: String!
        link: String
        page_number: Int
        per_page: Int
        total: Int 
        total_pages: Int
        ): PlantConnection
}

type PlantConnection {
    cursor: String
    hasMore: Boolean
    plants: [Plant]
}
